version: '3.5'
services:
  frontend:
    image: adopt-pets/frontend
    command: npm run serve
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"